### ISSUE TITLE
Visual style for canceled scheduleItems

### ISSUE THREAD

**Issue by knomepasi** [Ropecon/wp-kompassi-integration#77]
```css
#kompassi_schedule article[data-state="canceled"] {
  color: #777 !important;
}
#kompassi_schedule article[data-state="canceled"]::before {
  --kompassi-program-color: #ddd;
}
#kompassi_schedule article[data-state="canceled"] .title::before {
  display: inline-block;
  margin-right: 0.5em;
  content: "PERUTTU"; /* TODO: Translate */
  color: red;
  font-style: oblique;
}
```

![Image](https://github.com/user-attachments/assets/5de3a641-083b-4e0c-b265-ba027ccd26dd)
